version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: "@rollup/plugin-html"
    versions:
    - 0.2.0
    - 0.2.2
  - dependency-name: rollup-plugin-postcss
    versions:
    - 3.1.8
