name: Test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Borales/actions-yarn@master
      with:
        args: install
    - uses: Borales/actions-yarn@master
      with:
        args: test
