name: Update

on:
  schedule:
    - cron: 20 14 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: git checkout update-dependencies 2>/dev/null || true
    - uses: mikeal/npx@master
      with:
        args: yarn-up -u
    - uses: peter-evans/create-pull-request@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: update-dependencies
        PULL_REQUEST_TITLE: Update dependencies
        BRANCH_SUFFIX: none
        COMMIT_MESSAGE: Automatically update dependencies
        PULL_REQUEST_BODY:
